sentences = [
    "The sun set behind the distant hills.",
    "She ran through the park, feeling the wind in her hair.",
    "The aroma of fresh coffee filled the room.",
    "They sailed on the calm, blue ocean.",
    "He played his favorite song on the piano.",
    "The children laughed and played in the garden.",
    "The cat pounced on the playful kitten.",
    "Birds chirped in the trees all day.",
    "She watched the stars twinkle in the night sky.",
    "The fire crackled in the cozy cabin.",
    "They explored the hidden cave with flashlights.",
    "The flowers bloomed in a riot of colors.",
    "The car zoomed down the empty highway.",
    "He danced gracefully to the music.",
    "The puppy wagged its tail in excitement.",
    "The moon shone brightly over the quiet town.",
    "She hiked to the summit of the tall mountain.",
    "The snow fell gently, covering the ground in white.",
     # "He painted a beautiful landscape on the canvas.",
    "The waves crashed against the rocky shoreline.",


    # # "The children built a towering sandcastle on the beach.",
    # # "The aroma of freshly baked bread filled the kitchen.",
    # # "The birds sang melodiously in the morning.",
    # # "The baby slept soundly in the crib.",
    # # "They explored the dark forest with curiosity.",
    # # "The fireflies danced in the warm summer night.",
    # # "She jumped into the cool, refreshing pool.",
    # # "The cat purred contentedly on the couch.",
    # # "The city lights twinkled in the distance.",
    # # "He read a captivating mystery novel.",
    # # "The old bridge crossed the wide, rushing river.",
    # # "The rain poured down outside, but they stayed dry indoors.",
    # # "They rode their bikes through the scenic countryside.",
    # # "The wind rustled the leaves in the forest.",
    # # "She sang her favorite song with enthusiasm.",
    # # "The dog barked excitedly at the mailman.",
    # # "The train rumbled down the tracks with a roar.",
    # # "He swam in the clear, blue lake.",
    # # "The river flowed gently through the serene valley.",
    # # "The snowflakes fell softly, covering the world in white.",
    # # "She rode her skateboard down the steep hill.",
    # # "The old tree stood tall and majestic.",
    # # "The coffee brewed, filling the room with its aroma.",
    # # "The children played tag in the sunny meadow.",
    # # "The boat sailed on the calm, peaceful lake.",
    # # "He rode his horse through the open field.",
    # # "The squirrel chattered noisily in the tree.",
    # # "She danced gracefully under the starry night sky.",
    # # "The rain pattered softly on the roof.",
    # # "They explored the ancient ruins with wonder.",

















    "The sun shone brightly on the snowy mountain.",
    "The puppy wagged its tail with excitement.",
    "Snow fell gently all day.",
    "Flowers bloomed brightly in the park.",
    "A fire crackled in the cozy cabin.",
    "Children watched in awe as the fireworks lit up the night.",
    "Birds chirped in the garden.",
    "They sailed on the calm ocean.",
    "The piano played a soothing melody.",
    "The colors of the sunset were breathtaking.",
    "The children played in the park all day.",
    "The hidden cave was a mysterious place.",
    "The kitten pounced on its favorite toy.",
    "The highway stretched endlessly in front of them.",
    "The moon rose over the mountain.",
    "The wind rustled through the trees.",
    "Music filled the air in the concert hall.",
    "The car zoomed down the highway.",
    "The ocean was a deep shade of blue.",
    "The cat curled up in the cozy cabin.",
    "They hiked to the summit of the mountain.",
    "The puppy ran through the snow.",
    "The fire provided warmth in the cabin.",
    "The children laughed and played in the park.",
    "The garden was filled with colorful flowers.",
    "The kitten's playful antics brought joy to the family.",
    "The puppy's tail wagged with happiness.",
    "Snow fell gently on the ground.",
    "They explored the hidden cave with flashlights.",
    "The mountain was covered in a blanket of snow.",
    "The ocean waves danced gracefully.",
    "The children watched the riot of colors in the sky.",
    "The sun shone brightly on the beach.",
    "The cat pounced on a passing butterfly.",
    "The moon cast a soft glow over the landscape.",
    "The puppy's excitement was contagious.",
    "The fire crackled in the fireplace.",
    "They hiked to the summit of the mountain with their children.",
    "The car sped down the highway with the wind in their hair.",
    "Music filled the cabin as they played the piano.",
    "The garden was full of tall trees.",
    "They watched the birds in the garden.",
    "The stars twinkled brightly in the night sky.",
    "The puppy ran through the snow with joy.",
    "The cat's tail flicked in amusement.",
    "The children played in the park with enthusiasm.",
    "The fire in the cabin kept them warm.",
    "They gazed at the ocean and felt a sense of calm."
]